name: CI

on:
  push:
    branches:
      - main

jobs:
  ship_it:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: core
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - name: 🔨 Install Dependencies 🔨
        run: sudo apt-get update && sudo apt-get install make
      - name: 🚀 Deploy 🚀
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: make deploy
