name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Create '.env' file for vite
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_API_HOST: ${{ secrets.VITE_API_HOST }}
          file_name: .env
          fail_on_empty: true
      - name: 🚀 Deploy 🚀
        run: make deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
